### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 3000
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000001"
}

### get accounts
GET http://localhost:8080/account?user_id=1
Accept: application/json


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ea5649c1ad634e94bdf533ca1abc02ed",
  "accountNumber": "1000000000",
  "amount": 3000
}

### get transactions
GET http://localhost:8080/transaction/b068a4b47b33451483f1f11f900c023d
Accept: application/json
